jdk: 
  - openjdk8
language: java
script: 
  - "cd src"
  - "chmod +x gradlew"
  - "./gradlew run"
  - "./gradlew test"
notifications:
  email: false
- name: Coveralls GitHub Action
  uses: coverallsapp/github-action@v1.1.2
