jdk: 
  - openjdk8
language: java
script: 
  - "cd src"
  - "mkdir build/reports/jacoco/test/html"
  - "chmod +x gradlew"
  - "./gradlew run"
  - "./gradlew test"
  - "gradlew jacocoTestReport coveralls"
notifications:
  email: false
