jdk: 
  - openjdk8
language: java
script: 
  - "cd src"
  - "mkdir -p build/reports/jacoco/test/html"
  - "chmod +x gradlew"
  - "./gradlew run"
  - "./gradlew test"
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false