jdk: 
  - openjdk8
language: java
script: 
  - "cd src"
  - "chmod +x gradlew"
  - "./gradlew run"
  - "./gradlew test"
  - "gradlew jacocoTestReport coveralls --project-cache-dir=../cache"
notifications:
  email: false
