jdk: 
  - openjdk8
language: java
script: 
  - "cd src"
  - "COVERALLS_REPO_TOKEN=f4Ez1baiH7DNTEhAB3wNSo7zWzkg0bT84"
  - "chmod +x gradlew"
  - "./gradlew run"
  - "./gradlew test"
  - "./gradlew jacocoTestReport coveralls"
notifications:
  email: false
